markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: marisooo
host: mariso.tk
desc: Just record something.

custom:
    category:
        saying: 杂谈录
	thinking: 勤思考
	experience: 经验说
	discovery: 新技术
	criticism: 吐槽帝
    categories:
      - name:  saying
        title: 杂谈录

      - name: thinking
        title: 勤思考

      - name: experience
        title: 经验说

      - name: discovery
        title: 新技术

      - name: criticism
        title: 吐槽帝

    scrollingLoadCount: 0                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: marisooo
        email: marisooolili@gmail.com
        disqus: mariso              # Disqus缩略标识
        gcse: 007495367908009868948:czu1rxexkok     # Google自定义搜索标识ID
        github: marisooo                 # GitHub账号
        gravatar: 25336ab55348042ebb8450ccb486016d  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
