markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: marisooo
host: mariso.tk
desc: Just record something.

custom:
    category:
        thinking: 闭门思考
        experience: 问题即经验
        discovery: 日新月异
        criticism: 非专业吐槽
    categories:
      - name:  thinking
        title: 闭门思考

      - name:  experience
        title: 问题即经验

      - name:  discovery
        title: 日新月异

      - name:  criticism
        title: 非专业吐槽

    scrollingLoadCount: 1                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: marisooo
        email: marisooolili@gmail.com
        disqus: mariso              # Disqus缩略标识
        gcse: 007495367908009868948:czu1rxexkok     # Google自定义搜索标识ID
        github: marisooo                 # GitHub账号
        gravatar: 130a34668b1d7690d530cf3bfc65c814  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
